import type { MsfsAction } from "./types";

export const msfsActions: MsfsAction[] = [
  {
    id: "auto-start",
    name: "Auto-Start Engines",
    description: "Starts the plane for you. Do this first!",
    category: "systems",
    device: "KEYBOARD",
    icon: "zap",
    msfsPath: "Controls → Keyboard → Auto Start",
  },
  {
    id: "master-battery",
    name: "Master Battery",
    description: "Turns on the plane's power.",
    category: "systems",
    device: "KEYBOARD",
    icon: "battery",
    msfsPath: "Controls → Keyboard → Master Battery",
  },
  {
    id: "parking-brake",
    name: "Parking Brake",
    description: "Stops the plane from rolling on the ground.",
    category: "ground",
    device: "KEYBOARD",
    icon: "circle-parking",
    msfsPath: "Controls → Keyboard → Parking Brake",
  },
  {
    id: "throttle-idle",
    name: "Throttle to Idle",
    description: "Pull power back so engines are quiet and still.",
    category: "ground",
    device: "THROTTLE",
    icon: "gauge",
    msfsPath: "Controls → Throttle → Axis",
  },
  {
    id: "move-forward",
    name: "Move Forward",
    description: "Roll forward slowly on the ground.",
    category: "ground",
    device: "THROTTLE",
    icon: "arrow-up",
    msfsPath: "Controls → Throttle → Increase / F3",
  },
  {
    id: "slow-down",
    name: "Slow Down",
    description: "Ease off the power to go slower.",
    category: "ground",
    device: "THROTTLE",
    icon: "arrow-down",
    msfsPath: "Controls → Throttle → Decrease / F2",
  },
  {
    id: "brakes",
    name: "Brakes",
    description: "Hold to slow down or stop — like a car brake.",
    category: "ground",
    device: "KEYBOARD",
    icon: "octagon",
    msfsPath: "Controls → Keyboard → Brakes",
  },
  {
    id: "steer-ground",
    name: "Steer on Ground",
    description: "Twist to turn left or right while taxiing.",
    category: "ground",
    device: "JOYSTICK",
    icon: "rotate-cw",
    msfsPath: "Controls → Joystick → Rudder Axis (twist)",
  },
  {
    id: "pushback",
    name: "Pushback from Gate",
    description: "A truck pushes your plane away from the gate.",
    category: "ground",
    device: "KEYBOARD",
    icon: "plane",
    msfsPath: "Controls → Keyboard → Pushback",
  },
  {
    id: "full-throttle",
    name: "Full Throttle",
    description: "Push power up for takeoff!",
    category: "air",
    device: "THROTTLE",
    icon: "gauge",
    msfsPath: "Controls → Throttle → Axis",
  },
  {
    id: "rotate",
    name: "Pull Up / Rotate",
    description: "Gently pull back when fast enough to lift off.",
    category: "air",
    device: "JOYSTICK",
    icon: "arrow-up-from-line",
    msfsPath: "Controls → Joystick → Elevator Axis",
  },
  {
    id: "wings-level",
    name: "Keep Wings Level",
    description: "Tilt the stick to stay straight as you climb.",
    category: "air",
    device: "JOYSTICK",
    icon: "move-horizontal",
    msfsPath: "Controls → Joystick → Aileron Axis",
  },
  {
    id: "gear-toggle",
    name: "Landing Gear",
    description: "Put wheels up after takeoff. Put wheels down before landing!",
    category: "air",
    device: "KEYBOARD",
    icon: "cog",
    msfsPath: "Controls → Keyboard → Landing Gear",
  },
  {
    id: "flaps-up",
    name: "Flaps Up",
    description: "Fold flaps in after you are climbing.",
    category: "air",
    device: "KEYBOARD",
    icon: "layers",
    msfsPath: "Controls → Keyboard → Flaps Up",
  },
  {
    id: "flaps-down",
    name: "Flaps Down",
    description: "Extend flaps to slow down for landing.",
    category: "air",
    device: "KEYBOARD",
    icon: "chevrons-down",
    msfsPath: "Controls → Keyboard → Flaps Down",
  },
  {
    id: "pitch",
    name: "Pitch Up / Down",
    description: "Point the nose up to climb or down to go lower.",
    category: "air",
    device: "JOYSTICK",
    icon: "arrow-up-from-line",
    msfsPath: "Controls → Joystick → Elevator Axis",
  },
  {
    id: "bank",
    name: "Bank / Turn",
    description: "Tilt the plane left or right to turn.",
    category: "air",
    device: "JOYSTICK",
    icon: "move-horizontal",
    msfsPath: "Controls → Joystick → Aileron Axis",
  },
  {
    id: "rudder",
    name: "Rudder",
    description: "Keeps the plane pointed where you want.",
    category: "air",
    device: "JOYSTICK",
    icon: "rotate-cw",
    msfsPath: "Controls → Joystick → Rudder Axis",
  },
  {
    id: "throttle-adjust",
    name: "Change Speed",
    description: "Move the lever to go faster or slower in the air.",
    category: "air",
    device: "THROTTLE",
    icon: "gauge",
    msfsPath: "Controls → Throttle → Axis",
  },
  {
    id: "autopilot",
    name: "Autopilot",
    description: "Let MSFS help fly straight and level.",
    category: "air",
    device: "KEYBOARD",
    icon: "zap",
    msfsPath: "Controls → Keyboard → Autopilot",
  },
  {
    id: "show-map",
    name: "Show Map",
    description: "Open the map to see where you are.",
    category: "camera",
    device: "KEYBOARD",
    icon: "map",
    msfsPath: "Controls → Keyboard → VFR Map",
  },
  {
    id: "reduce-throttle",
    name: "Reduce Throttle",
    description: "Pull power back to slow down for landing.",
    category: "air",
    device: "THROTTLE",
    icon: "gauge",
    msfsPath: "Controls → Throttle → Axis",
  },
  {
    id: "flare",
    name: "Flare on Landing",
    description: "Gently pull back right before the wheels touch.",
    category: "air",
    device: "JOYSTICK",
    icon: "wind",
    msfsPath: "Controls → Joystick → Elevator Axis",
  },
  {
    id: "spoilers",
    name: "Spoilers",
    description: "Pop up wing panels to slow down after landing.",
    category: "air",
    device: "KEYBOARD",
    icon: "chevrons-up",
    msfsPath: "Controls → Keyboard → Spoilers",
  },
  {
    id: "leave-runway",
    name: "Leave the Runway",
    description: "Use low power and steer off the runway.",
    category: "ground",
    device: "THROTTLE",
    icon: "signpost",
    msfsPath: "Controls → Throttle + Rudder",
  },
  {
    id: "follow-taxi-line",
    name: "Follow Taxi Line",
    description: "Steer gently along the yellow path.",
    category: "ground",
    device: "JOYSTICK",
    icon: "route",
    msfsPath: "Controls → Joystick → Rudder Axis",
  },
  {
    id: "outside-camera",
    name: "Outside Camera",
    description: "See your plane from outside while taxiing.",
    category: "camera",
    device: "KEYBOARD",
    icon: "camera",
    msfsPath: "Controls → Keyboard → Toggle Cockpit",
  },
  {
    id: "taxi-speed",
    name: "Taxi Speed",
    description: "Stay slow on the ground — about 10–15 knots.",
    category: "ground",
    device: "THROTTLE",
    icon: "gauge",
    msfsPath: "Controls → Throttle → Axis",
  },
  {
    id: "cockpit-toggle",
    name: "Cockpit / Outside View",
    description: "Switch between inside and outside views.",
    category: "camera",
    device: "KEYBOARD",
    icon: "eye",
    msfsPath: "Controls → Keyboard → Toggle Cockpit",
  },
  {
    id: "look-around",
    name: "Look Around",
    description: "Hold right-click and move the mouse to look.",
    category: "camera",
    device: "MOUSE",
    icon: "mouse-pointer",
    msfsPath: "Controls → Mouse → Look",
  },
  {
    id: "quick-look",
    name: "Quick Look",
    description: "Snap your view in a direction fast.",
    category: "camera",
    device: "KEYBOARD",
    icon: "move-horizontal",
    msfsPath: "Controls → Keyboard → Quick View",
  },
  {
    id: "drone-camera",
    name: "Drone Camera",
    description: "Fly a free camera around your plane.",
    category: "camera",
    device: "KEYBOARD",
    icon: "camera",
    msfsPath: "Controls → Keyboard → Drone Camera",
  },
  {
    id: "zoom-in",
    name: "Zoom In",
    description: "Get a closer look.",
    category: "camera",
    device: "KEYBOARD",
    icon: "zoom-in",
    msfsPath: "Controls → Keyboard → Zoom In",
  },
  {
    id: "zoom-out",
    name: "Zoom Out",
    description: "See more of the view.",
    category: "camera",
    device: "KEYBOARD",
    icon: "zoom-in",
    msfsPath: "Controls → Keyboard → Zoom Out",
  },
  {
    id: "reset-view",
    name: "Reset View",
    description: "Go back to the normal pilot view.",
    category: "camera",
    device: "KEYBOARD",
    icon: "refresh-cw",
    msfsPath: "Controls → Keyboard → Reset Cockpit View",
  },
];

export const actionMap = Object.fromEntries(
  msfsActions.map((action) => [action.id, action])
) as Record<string, MsfsAction>;

export function getAction(id: string): MsfsAction | undefined {
  return actionMap[id];
}

export function getActionsByCategory(category: MsfsAction["category"]) {
  return msfsActions.filter((action) => action.category === category);
}

export function getActionsByDevice(device: MsfsAction["device"]) {
  return msfsActions.filter((action) => action.device === device);
}
